-- Snowflake permission grants
-- PATCHIT auto-fix: grant missing privileges (snowflake:analytics_schema_load)
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE PIPELINE_ROLE;
GRANT USAGE ON DATABASE ANALYTICS_DB TO ROLE PIPELINE_ROLE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE ANALYTICS_DB TO ROLE PIPELINE_ROLE;
GRANT SELECT ON ALL TABLES IN DATABASE ANALYTICS_DB TO ROLE PIPELINE_ROLE;
